services:
    symfonian_id.admin.congiration.factory:
        class: Symfonian\Indonesia\AdminBundle\Configuration\ConfigurationFactory
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@form.factory'

    symfonian_id.admin.congiration.configurator:
        class: Symfonian\Indonesia\AdminBundle\Configuration\Configurator
        calls:
            - [setContainer, ['@service_container']]
            - [setFilter, ['%symfonian_id.admin.filter%']]
        arguments:
            - ['@annotation_reader']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 255 }

    symfonian_id.admin.congiration.grid_configurator:
        class: Symfonian\Indonesia\AdminBundle\Configuration\GridConfigurator
        calls:
            - [setFilter, ['%symfonian_id.admin.filter%']]
        arguments:
            - '@annotation_reader'
            - '@symfonian_id.admin.congiration.factory'

    symfonian_id.admin.annotation.crud:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Crud
        calls:
            - [setContainer, ['@service_container']]
            - [setFormFactory, ['@form.factory']]
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.grid:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Grid
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.page:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Page
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util
        tags:
            - { name: siab.config }