services:
    symfonian_id.admin.congiration.configurator:
        class: Symfonian\Indonesia\AdminBundle\Configuration\Configurator
        arguments:
            - '@kernel'
            - '@symfonian_id.admin.extractor.extractor_factory'
            - '@form.factory'
            - '%symfonian_id.admin.driver%'
        calls:
            - [setContainer, ['@service_container']]
            - [setFilter, ['%symfonian_id.admin.filter%']]
            - [setTemplate, ['@symfonian_id.admin.view.template']]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: configureGrid, priority: 1027 }
            - { name: kernel.event_listener, event: kernel.controller, method: configureTemplate, priority: 1027 }
            - { name: kernel.event_listener, event: kernel.controller, method: parseAnnotation, priority: -1027 }

    symfonian_id.admin.annotation.crud:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Crud
        calls:
            - [setContainer, ['@service_container']]
            - [setTemplate, ['@symfonian_id.admin.view.template']]
            - [setFormFactory, ['@form.factory']]
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.grid:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Grid
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.page:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Page
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.plugins:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Plugins
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util.autocomplete:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util\AutoComplete
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util.date_picker:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util\DatePicker
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util.external_javascript:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util\ExternalJavascript
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util.upload:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util\Upload
        tags:
            - { name: siab.config }
