services:
    symfonian_id.admin.congiration.configurator:
        class: Symfonian\Indonesia\AdminBundle\Configuration\Configurator
        arguments:
            - '@kernel'
            - '@symfonian_id.admin.extractor.extractor_factory'
            - '@form.factory'
        calls:
            - [setContainer, ['@service_container']]
            - [setFilter, ['%symfonian_id.admin.filter%']]
            - [setTemplate, [{new: '%symfonian_id.admin.themes.new_view%', edit: '%symfonian_id.admin.themes.edit_view%', show: '%symfonian_id.admin.themes.show_view%', list: '%symfonian_id.admin.themes.list_view%'}]]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: configureGrid, priority: 255 }
            - { name: kernel.event_listener, event: kernel.controller, method: configureTemplate, priority: 255 }
            - { name: kernel.event_listener, event: kernel.controller, method: parseAnnotation, priority: -255 }

    symfonian_id.admin.annotation.crud:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Crud
        calls:
            - [setContainer, ['@service_container']]
            - [setFormFactory, ['@form.factory']]
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.grid:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Grid
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.page:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Page
        tags:
            - { name: siab.config }

    symfonian_id.admin.annotation.util:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Util
        tags:
            - { name: siab.config }