services:
    symfonian_id.admin.filter.orm.sort:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Orm\Sorter\FieldsSorter
        arguments:
            - '@symfonian_id.admin.manager.factory'
            - '@annotation_reader'
            - '@symfonian_id.admin.congiration.configurator'
            - '%symfonian_id.admin.driver%'

    symfonian_id.admin.filter.odm.sort:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Odm\Sorter\FieldsSorter
        arguments:
            - '@symfonian_id.admin.manager.factory'
            - '@annotation_reader'
            - '@symfonian_id.admin.congiration.configurator'
            - '%symfonian_id.admin.driver%'

    symfonian_id.admin.filter.orm.soft_deletable:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Orm\Filter\SoftDeletableFilter
        tags:
            - { name: siab.filter }

    symfonian_id.admin.filter.odm.soft_deletable:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Odm\Filter\SoftDeletableFilter
        tags:
            - { name: siab.filter }

    symfonian_id.admin.filter.orm.fields:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Orm\Filter\FieldsFilter
        tags:
            - { name: siab.filter }

    symfonian_id.admin.filter.odm.fields:
        class: Symfonian\Indonesia\AdminBundle\Doctrine\Odm\Filter\FieldsFilter
        tags:
            - { name: siab.filter }
