services:
    symfonian_id.admin.change_password_form:
        class: Symfonian\Indonesia\AdminBundle\Form\ChangePasswordType
        arguments:
            - '%symfonian_id.admin.user.user_entity%'
            - '%symfonian_id.admin.translation_domain%'
        tags:
            - { name: form.type }

    symfonian_id.admin.user_form:
        class: Symfonian\Indonesia\AdminBundle\Form\UserType
        arguments:
            - '%symfonian_id.admin.user.user_entity%'
            - '%symfonian_id.admin.translation_domain%'
            - '%security.role_hierarchy.roles%'
            - '%symfonian_id.admin.upload_dir%'
        tags:
            - { name: form.type }
