services:
#Symfony Listeners
    symfonian_id.admin.user_template_manipulator:
        class: Symfonian\Indonesia\AdminBundle\EventListener\UserConfigurationListener
        calls:
            - [setForm, ['%symfonian_id.admin.user.user_form%', '%symfonian_id.admin.user.user_entity%']]
            - [setView, ['%symfonian_id.admin.user.show_fields%', '%symfonian_id.admin.user.grid_fields%', '%symfonian_id.admin.user.grid_filters%']]
        arguments:
            - '@symfonian_id.admin.congiration.configurator'
            - '@kernel'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    symfonian_id.admin.profile_controller_compiler:
        class: Symfonian\Indonesia\AdminBundle\EventListener\ProfileConfigurationListener
        calls:
            - [setFormClass, ['%symfonian_id.admin.user.password_form%']]
            - [setProfileFields, ['%symfonian_id.admin.profile_fields%']]
        arguments:
            - '@symfonian_id.admin.congiration.configurator'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    symfonian_id.admin.configuration_cache_warmer:
        class: Symfonian\Indonesia\AdminBundle\Cache\ConfigurationCacheWarmer
        arguments:
            - '@symfonian_id.admin.congiration.configurator'
            - '@symfonian_id.admin.extractor.extractor_factory'
            - '@form.factory'
        calls:
            - [setContainer, ['@service_container']]
            - [setFilter, ['%symfonian_id.admin.filter%']]
            - [setTemplate, ['@symfonian_id.admin.view.template']]
            - [setForm, ['%symfonian_id.admin.user.user_form%', '%symfonian_id.admin.user.user_entity%']]
            - [setView, ['%symfonian_id.admin.user.show_fields%', '%symfonian_id.admin.user.grid_fields%', '%symfonian_id.admin.user.grid_filters%']]
            - [setProfileForm, ['%symfonian_id.admin.user.password_form%']]
            - [setProfileFields, ['%symfonian_id.admin.profile_fields%']]
        tags:
            - { name: kernel.cache_warmer }

    symfonian_id.admin.variable_registrator:
        class: Symfonian\Indonesia\AdminBundle\EventListener\TwigVariableListener
        calls:
            - [setTitle, ['%symfonian_id.admin.app_title%']]
            - [setShortTitle, ['%symfonian_id.admin.app_short_title%']]
            - [setDateTimeFormat, ['%symfonian_id.admin.date_time_format%']]
            - [setMenu, ['%symfonian_id.admin.menu%']]
            - [setLocale, ['%locale%']]
            - [setTranslationDomain, ['%symfonian_id.admin.translation_domain%']]
        arguments:
            - '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

#Symfonian Indonesia Listeners
    symfonian_id.admin.delete_user:
        class: Symfonian\Indonesia\AdminBundle\EventListener\DeleteUserListener
        arguments:
            - '@security.token_storage'
            - '@translator'
            - '%symfonian_id.admin.translation_domain%'
        tags:
            - { name: kernel.event_listener, event: siab.pre_delete, method: onDeleteUser, priority: 1027 }

    symfonian_id.admin.set_timestamp:
        class: Symfonian\Indonesia\AdminBundle\EventListener\SetTimestampListener
        arguments:
            - '@security.token_storage'
        tags:
            - { name: kernel.event_listener, event: siab.pre_save, method: onPreSaveUser, priority: 1027 }

    symfonian_id.admin.update_user:
        class: Symfonian\Indonesia\AdminBundle\EventListener\UpdateUserListener
        arguments:
            - '%symfonian_id.admin.user.auto_enable%'
        tags:
            - { name: kernel.event_listener, event: siab.pre_save, method: onPreSaveUser, priority: 1027 }

    symfonian_id.admin.upload_avatar:
        class: Symfonian\Indonesia\AdminBundle\EventListener\FileUploaderListener
        calls:
            - [setUploadField, []]
        arguments:
            - '@symfonian_id.admin.congiration.configurator'
            - '@symfonian_id.admin.handler.upload'
            - '%symfonian_id.admin.upload_dir%'
        tags:
            - { name: kernel.event_listener, event: siab.pre_save, method: onPreSave, priority: 1027 }

    symfonian_id.admin.sort_query:
        class: Symfonian\Indonesia\AdminBundle\EventListener\EnableFieldsSorterListener
        calls:
            - [setContainer, ['@service_container']]
        arguments:
            - '@symfonian_id.admin.manager.factory'
            - '@annotation_reader'
            - '%symfonian_id.admin.driver%'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: siab.filter_query, method: onFilterQuery, priority: 1023 }

    symfonian_id.admin.soft_deletable_filter:
        class: Symfonian\Indonesia\AdminBundle\EventListener\EnableSoftDeletableFilterListener
        arguments:
            - '@symfonian_id.admin.manager.factory'
            - '%symfonian_id.admin.driver%'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    symfonian_id.admin.fields_filter:
        class: Symfonian\Indonesia\AdminBundle\EventListener\EnableFieldsFilterListener
        arguments:
            - '@symfonian_id.admin.manager.factory'
            - '@annotation_reader'
            - '@symfonian_id.admin.congiration.configurator'
            - '%symfonian_id.admin.driver%'
            - '%symfonian_id.admin.date_time_format%'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
