services:
    symfonian_id.admin.home_route_loader:
        class: Symfonian\Indonesia\AdminBundle\Route\SiabRouteLoader
        arguments:
            - '@controller_name_converter'
            - '@routing.resolver'
            - '@symfonian_id.admin.extractor.extractor_factory'
            - '@kernel'
        tags:
            - { name: routing.loader }

    symfonian_id.admin.handler.crud:
        class: Symfonian\Indonesia\AdminBundle\Handler\CrudHandler
        arguments:
            - '@security.token_storage'
            - '@symfonian_id.admin.manager.factory'
        calls:
            - [setContainer, ['@service_container']]

    symfonian_id.admin.handler.upload:
        class: Symfonian\Indonesia\AdminBundle\Handler\UploadHandler

    symfonian_id.admin.manager.factory:
        class: Symfonian\Indonesia\AdminBundle\Manager\ManagerFactory

    symfonian_id.admin.view.view:
        class: Symfonian\Indonesia\AdminBundle\View\View

    symfonian_id.admin.view.template:
        class: Symfonian\Indonesia\AdminBundle\View\Template
        calls:
            - [setCreate, ['%symfonian_id.admin.themes.new_view%']]
            - [setBulkCreate, ['%symfonian_id.admin.themes.bulk_new%']]
            - [setEdit, ['%symfonian_id.admin.themes.edit_view%']]
            - [setShow, ['%symfonian_id.admin.themes.show_view%']]
            - [setList, ['%symfonian_id.admin.themes.list_view%']]
