services:
    symfonian_id.admin.annotation:
        class: Symfonian\Indonesia\AdminBundle\Annotation\Reader\AnnotationReader
        arguments:
            - '@annotation_reader'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: -255 }

    symfonian_id.admin.delete_user:
        class: Symfonian\Indonesia\AdminBundle\EventListener\DeleteUserListener
        arguments:
            - '@service_container'
            - '@security.token_storage'
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: symfonian_id.admin.pre_delete_event, method: onDeleteUser }

    symfonian_id.admin.update_user:
        class: Symfonian\Indonesia\AdminBundle\EventListener\UpdateUserListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: symfonian_id.admin.pre_save_event, method: onPreSaveUser }

    symfonian_id.admin.remove_password_field:
        class: Symfonian\Indonesia\AdminBundle\EventListener\RemovePasswordFieldListener
        tags:
            - { name: kernel.event_listener, event: symfonian_id.admin.pre_form_submit_event, method: onPreCreateForm }

    symfonian_id.admin.controller_default_view_pass:
        class: Symfonian\Indonesia\AdminBundle\Compiler\DefaultTemplateRegister
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 255 }

    symfonian_id.admin.user_controller_dependency_pass:
        class: Symfonian\Indonesia\AdminBundle\Compiler\UserControllerRegister
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }

    symfonian_id.admin.index_controller_dependency_pass:
        class: Symfonian\Indonesia\AdminBundle\Compiler\ProfileControllerRegister
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 0 }

    symfonian_id.admin.twig_global_variable_pass:
        class: Symfonian\Indonesia\AdminBundle\Compiler\TwigGlobalVariableRegister
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    symfonian_id.admin.menu:
        class: Symfonian\Indonesia\AdminBundle\Menu\Builder
        arguments:
            - '@router'
            - '@service_container'

    symfonian_id.admin.main_menu:
        class: Knp\Menu\MenuItem
        factory_service: symfonian_id.admin.menu
        factory_method: mainMenu
        arguments:
            - '@knp_menu.factory'
            - []
        tags:
            - { name: knp_menu.menu, alias: symfonian_indonesia_admin_main_menu }

    symfonian_id.admin.change_password_form:
        class: Symfonian\Indonesia\AdminBundle\Form\ChangePasswordType
        arguments:
            - '@service_container'
        tags:
            - { name: form.type }

    symfonian_id.admin.generic_form:
        class: Symfonian\Indonesia\AdminBundle\Form\GenericFormType
        arguments:
            - '@service_container'
        tags:
            - { name: form.type }

    symfonian_id.admin.user_form:
        class: Symfonian\Indonesia\AdminBundle\Form\UserType
        arguments:
            - '@service_container'
            - '%security.role_hierarchy.roles%'
        tags:
            - { name: form.type }

    symfonian_id.admin.home_route_loader:
        class: Symfonian\Indonesia\AdminBundle\Route\HomeRouteLoader
        arguments:
            - '@service_container'
        tags:
            - { name: routing.loader }

    symfonian_id.admin.twig.is_number:
        class: Symfonian\Indonesia\AdminBundle\Twig\NumberExtension\NumberTest
        tags:
            - { name: twig.extension }

    symfonian_id.admin.twig.is_valid_interval:
        class: Symfonian\Indonesia\AdminBundle\Twig\DateExtension\ValidateIntervalFunction
        tags:
            - { name: twig.extension }

    symfonian_id.admin.twig.ucwords:
        class: Symfonian\Indonesia\AdminBundle\Twig\StringExtension\UcWordsFilter
        tags:
            - { name: twig.extension }

    symfonian_id.admin.handler.crud:
        class: Symfonian\Indonesia\AdminBundle\Handler\CrudHandler
        arguments:
            - '@service_container'

    symfonian_id.admin.cache_listener:
        class: Symfonian\Indonesia\AdminBundle\EventListener\CacheListener
        arguments:
            - '@service_container'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
