services:
    ihsan.simple_crud.crud_annotation_reader:
        class: Ihsan\SimpleAdminBundle\EventListener\AnnotationListener
        arguments:
            - @annotation_reader
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller", method: "onKernelController" }
