services:
    symfonian_id.admin.home_route_loader:
        class: Symfonian\Indonesia\AdminBundle\Route\SiabRouteLoader
        arguments:
            - '@controller_name_converter'
            - '@routing.resolver'
            - '@symfonian_id.admin.extractor.extractor_factory'
            - '@kernel'
        tags:
            - { name: routing.loader }

    symfonian_id.admin.handler.crud:
        class: Symfonian\Indonesia\AdminBundle\Handler\CrudHandler
        arguments:
            - '@security.token_storage'
        calls:
            - [setContainer, ['@service_container']]

    symfonian_id.admin.handler.upload:
        class: Symfonian\Indonesia\AdminBundle\Handler\UploadHandler